name:  synchro-repo

on: [ push, delete, create ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
        
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Deploy
        env:
           MESSAGEDATA: ${{ github.event.head_commit.message }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main
          commit-message: ${{ env.MESSAGEDATA }}
          folder: .
          repository-name: 'tinymce-plugin/tinymce-plugin.github.io'
